### ISSUE TITLE
angular is not defined

### ISSUE THREAD

**Issue by takuoka** [maxigimenez/github-notify-desktop#5]
> $ npm run start;
> 
> > github-desktop-menu@1.0.0 start /Users/Takuya/Creation/Clone/github-notify-desktop
> > electron .
> 
> [4892:1127/124924:INFO:renderer_main.cc(200)] Renderer process started
> [4887:1127/124924:INFO:CONSOLE(3)] "Uncaught ReferenceError: angular is not defined", source: file:///Users/Takuya/Creation/Clone/github-notify-desktop/assets/js/app.js (3)
> [4887:1127/124924:INFO:CONSOLE(3)] "Uncaught ReferenceError: angular is not defined", source: file:///Users/Takuya/Creation/Clone/github-notify-desktop/assets/js/config.js (3)
> [4887:1127/124924:INFO:CONSOLE(3)] "Uncaught ReferenceError: angular is not defined", source: file:///Users/Takuya/Creation/Clone/github-notify-desktop/assets/js/list.js (3)
> [4887:1127/124924:INFO:CONSOLE(3)] "Uncaught ReferenceError: angular is not defined", source: file:///Users/Takuya/Creation/Clone/github-notify-desktop/assets/js/setup.js (3)

**Comment by maxigimenez** [comment]
Check if the `node_modules` and `bower_components` folders exists in the root of the project. If not run again `npm install`.

**Comment by takuoka** [comment]
Thanks. It works.

> npm install -g bower

**Comment by maxigimenez** [comment]
Awesome!
